### ISSUE TITLE
Fails with self-referencing data class

### ISSUE THREAD

**Issue by waltkb** [SMILEY4/schema-kenerator#1]
When updating to ktor-swagger-ui 3.0.0, the following 2 issues came up with the schema generation:

### 1. Self-referencing data class

```kotlin
@Serializable
data class A(
    val value1: String? = null,
    val value2: A? = null,
)
```
```kotlin
routing {
    post("test-api", {
        request {
            body<A>()
        }
    }) {}
}
```

This now causes:

```
10:48:38.872350899 ERROR [          D-worker-2] : i.g.s.k.SwaggerPlugi : Error during openapi-generation
java.lang.NullPointerException
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep$referenceDefinitionsReferences$json$1.invoke(SwaggerSchemaCompileStep.kt:84)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep$referenceDefinitionsReferences$json$1.invoke(SwaggerSchemaCompileStep.kt:82)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep.replaceReferences(SwaggerSchemaCompileStep.kt:158)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep.replaceReferences(SwaggerSchemaCompileStep.kt:162)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep.referenceDefinitionsReferences(SwaggerSchemaCompileStep.kt:82)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep.compileReferencing(SwaggerSchemaCompileStep.kt:47)
at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaCompileStep.compileReferencingRoot(SwaggerSchemaCompileStep.kt:60)
at io.github.smiley4.schemakenerator.swagger.StepsKt.compileReferencingRoot(steps.kt:89)
at io.github.smiley4.schemakenerator.swagger.StepsKt.compileReferencingRoot$default(steps.kt:88)
at io.github.smiley4.ktorswaggerui.data.SchemaConfigData$Companion$DEFAULT$1.invoke(SchemaConfigData.kt:35)
at io.github.smiley4.ktorswaggerui.data.SchemaConfigData$Companion$DEFAULT$1.invoke(SchemaConfigData.kt:26)
at io.github.smiley4.ktorswaggerui.builder.schema.SchemaContextImpl.generateSchema(SchemaContextImpl.kt:120)
at io.github.smiley4.ktorswaggerui.builder.schema.SchemaContextImpl.generateSchema(SchemaContextImpl.kt:68)
at io.github.smiley4.ktorswaggerui.builder.schema.SchemaContextImpl.add(SchemaContextImpl.kt:54)
at io.github.smiley4.ktorswaggerui.SwaggerPluginKt.buildOpenApiSpec(SwaggerPlugin.kt:94)
at io.github.smiley4.ktorswaggerui.SwaggerPluginKt.buildOpenApiSpecs(SwaggerPlugin.kt:85)
at io.github.smiley4.ktorswaggerui.SwaggerPluginKt.access$buildOpenApiSpecs(SwaggerPlugin.kt:1)
at io.github.smiley4.ktorswaggerui.SwaggerPluginKt$SwaggerUI$2$1.invoke(SwaggerPlugin.kt:66)
at io.github.smiley4.ktorswaggerui.SwaggerPluginKt$SwaggerUI$2$1.invoke(SwaggerPlugin.kt:58)
at io.ktor.server.application.hooks.MonitoringEvent$install$1.invoke(CommonHooks.kt:63)
at io.ktor.server.application.hooks.MonitoringEvent$install$1.invoke(CommonHooks.kt:62)
at io.ktor.events.Events.raise(Events.kt:49)
at io.ktor.events.EventsKt.raiseCatching(Events.kt:70)
at io.ktor.events.EventsKt.raiseCatching$default(Events.kt:68)
at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.safeRiseEvent(ApplicationEngineEnvironmentReloading.kt:206)
at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:326)
at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:150)
at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:277)
```

I also tried to switch the generator like this:
```kotlin
install(SwaggerUI) {
    schemas {
        generator = { type ->
            type.processKotlinxSerialization()
                .generateSwaggerSchema()
                .withAutoTitle(TitleType.SIMPLE)
                .compileReferencingRoot()
        }
    }
...
```
This will then not cause an exception during initial schema generation, but when accessing  `GET /api.json`, it causes `java.util.NoSuchElementException: No api-spec with name 'api' registered.` (same error as below in 2. then).

### 2. Self-referencing data class (wrapped)

This is basically the same thing, but nested several layers deep:

```kotlin
@Serializable
data class A(
    val value1: String? = null,
    val value2: B? = null,
)

@Serializable
data class B(
    val value1: String? = null,
    val value2: List<B>? = null,
)
```
```kotlin
routing {
    post("test-api", {
        request {
            body<A>()
        }
    }) {}
}
```

This will not throw any error during the initial schema generation, but when trying to access the API, set up like this:
```kotlin
routing {
    route("swagger") {
        swaggerui("/api.json")
    }

    route("api.json") {
        openapispec()
    }
}
```

Will cause this when accessing `GET /api.json`:
```
java.util.NoSuchElementException: No api-spec with name 'api' registered.
	at io.github.smiley4.ktorswaggerui.routing.ApiSpec.get(ApiSpec.kt:21)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1$1.invokeSuspend(routing.kt:22)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1$1.invoke(routing.kt)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1$1.invoke(routing.kt)
	at io.ktor.server.response.ApplicationResponseFunctionsKt.respondText(ApplicationResponseFunctions.kt:139)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1.invokeSuspend(routing.kt:22)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1.invoke(routing.kt)
	at io.github.smiley4.ktorswaggerui.routing.RoutingKt$openApiSpec$2$1.invoke(routing.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
```

**Comment by SMILEY4** [comment]
Hi, thanks for reporting this issue.
I (think) i successfully fixed the bug and a new version should be available soon.
