### ISSUE TITLE
Field with Swagger annotation throws NumberFormatException

### ISSUE THREAD

**Issue by peterbb** [SMILEY4/schema-kenerator#8]
Hi! See this commit where I extend one of the unit tests:  https://github.com/peterbb/schema-kenerator/commit/7e27d7626911b1c9cfbda1a29d6797bf813ce991

That code throws this exception:
```
No exception expected, but a NumberFormatException was thrown.
java.lang.AssertionError: No exception expected, but a NumberFormatException was thrown.
	at io.github.smiley4.schemakenerator.test.SwaggerAnnotationsTest$1$2.invokeSuspend(SwaggerAnnotationsTest.kt:152)
	at io.github.smiley4.schemakenerator.test.SwaggerAnnotationsTest$1$2.invoke(SwaggerAnnotationsTest.kt)
	at io.github.smiley4.schemakenerator.test.SwaggerAnnotationsTest$1$2.invoke(SwaggerAnnotationsTest.kt)
	at io.kotest.core.spec.style.scopes.StringSpecRootScope$invoke$1.invokeSuspend(StringSpecRootScope.kt:71)
	at io.kotest.core.spec.style.scopes.StringSpecRootScope$invoke$1.invoke(StringSpecRootScope.kt)
	at io.kotest.core.spec.style.scopes.StringSpecRootScope$invoke$1.invoke(StringSpecRootScope.kt)
        ...
Caused by: java.lang.NumberFormatException
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:689)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:483)
	at java.base/java.math.BigDecimal.<init>(BigDecimal.java:889)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationStep.getMinimum(SwaggerSchemaAnnotationStep.kt:181)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationStep.access$getMinimum(SwaggerSchemaAnnotationStep.kt:33)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationStep$process$5.invoke(SwaggerSchemaAnnotationStep.kt:76)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationStep$process$5.invoke(SwaggerSchemaAnnotationStep.kt:51)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationUtils.iterateProperties(SwaggerSchemaAnnotationUtils.kt:17)
	at io.github.smiley4.schemakenerator.swagger.steps.SwaggerSchemaAnnotationStep.process(SwaggerSchemaAnnotationStep.kt:51)
```

In this case, it's crashing because `minimum` is not set in the annotation on the field, so it defaults to `""`. I guess something like this might be a fix: https://github.com/peterbb/schema-kenerator/commit/e1aff2f3f15534cad9de2391eae325a08b9353db.

**Comment by SMILEY4** [comment]
Hi,  thanks for reporting the problem.
Would you like to open a pr with your fix ?

**Comment by peterbb** [comment]
Yeah, I'll do that :)
